### ISSUE TITLE
Co zminit z pyformat.info

### ISSUE THREAD

**Issue by torsava** [frenzymadness/Advanced_PyLadies#12]
Zaklad:

    '{} {}'.format('one', 'two')
    '{1} {0}'.format('one', 'two')
    '{0!s} {0!r}'.format(Data())

Padding:

    '{:>10}'.format('test')
    '{:10}'.format('test')

Cisla:

    '{:d}'.format(42)
    '{:4d}'.format(42)
    '{:04d}'.format(42)
    '{:f}'.format(3.141592653589793)
    '{:06.2f}'.format(3.141592653589793)

Pojmenovane:

    '{first} {last}'.format(first='Hodor', last='Hodor!')

Pristup k slozitejsim strukturam:

    person = {'first': 'Jean-Luc', 'last': 'Picard'}
    data = [4, 8, 15, 16, 23, 42]
    class Plant(object):
        type = 'tree'
    '{p[first]} {p[last]} {d[4]} {d[5]} {p.type}'.format(p=person, d=data, p=Plant())

Datetime:

    from datetime import datetime
    '{:%Y-%m-%d %H:%M}'.format(datetime(2001, 2, 3, 4, 5))

A kdyby byl zajem tak mozna i zminit ze se da delat tohle (upravit priklad aby byl podobny tem vyse pouzitym):

    '{:{align}{width}}'.format('test', align='^', width='10')

**Comment by frenzymadness** [comment]
Hotovo a ještě něco málo jsem k tomu přidal, děkuji.
