### ISSUE TITLE
Jupyter Notebook intro review

### ISSUE THREAD

**Issue by frenzymadness** [frenzymadness/Advanced_PyLadies#2]
Můžete prosím @encukou, @hroncok a @Glutexo udělat rychlé review materiálů na zítřejší první hodiny Advace Pythonu v Ostravě? Klidně sem sepisujte i drobnosti nepo pošlete PR, ale startujeme zítra v 17:00, takže bych spíše potřeboval odhalit faktické chyby.

**Comment by hroncok** [comment]
https://github.com/frenzymadness/Advanced_PyLadies/blob/master/01_Jupyter_notebook_intro/index.md

**Comment by Glutexo** [comment]
#4
